export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <a href="/" className="text-sm text-zinc-400 hover:text-zinc-900 transition-colors mb-8 inline-block">&larr; Back to home</a>
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-zinc-400 mb-8">Last updated: April 10, 2026</p>

        <div className="prose prose-zinc prose-sm max-w-none space-y-6 text-zinc-600 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-zinc-900">1. What DigestPilot is</h2>
            <p>DigestPilot is an AI-powered email digest and productivity service. It reads your Gmail inbox (read-only), generates summaries, suggests replies, extracts calendar events, and tracks commitments. Digests are delivered via email on your chosen schedule.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">2. Your account</h2>
            <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 18 years old to use DigestPilot.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">3. Gmail access</h2>
            <p>By connecting your Gmail account, you grant DigestPilot read-only access to your emails. We use this access exclusively to provide the digest service. We do not send, delete, or modify any emails. You can revoke access at any time from your Google account settings or from the DigestPilot settings page.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">4. AI-generated content</h2>
            <p>Email summaries, reply suggestions, and commitment detection are generated by AI. While we strive for accuracy, AI-generated content may contain errors. You are responsible for reviewing any suggested replies before sending them. DigestPilot does not send emails on your behalf.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">5. Data and privacy</h2>
            <p>Your use of DigestPilot is also governed by our <a href="/privacy" className="text-blue-600 underline">Privacy Policy</a>. Email content is processed by AI to generate summaries and is not permanently stored in its original form.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">6. Service availability</h2>
            <p>We aim to provide reliable service but cannot guarantee 100% uptime. DigestPilot is provided "as is" without warranties of any kind. We may update, modify, or discontinue features at any time.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">7. Limitation of liability</h2>
            <p>DigestPilot is not liable for any missed emails, incorrect summaries, or actions taken based on AI-generated suggestions. You are responsible for verifying the accuracy of AI-generated content before acting on it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">8. Account deletion</h2>
            <p>You can delete your account at any time from the Settings page. This permanently removes all your data including summaries, commitments, and stored tokens.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">9. Changes to terms</h2>
            <p>We may update these terms from time to time. Continued use of DigestPilot after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-900">10. Contact</h2>
            <p>Questions? Email us at <a href="mailto:stefan.aberg84@gmail.com" className="text-blue-600 underline">stefan.aberg84@gmail.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
